### PR TITLE
[WIP] DiffEqUncertainty Tutorials

### PR DESCRIPTION
**Pull request by agerlach**
Includes basic introduction to `expectation()` and the `Koopman()` algorithm.

### CODE REVIEW

**Comment by agerlach** [comment]
Waiting for DEU PR merge and release. Then can update Project.toml. Otherwise, this should be ready.

**Comment by ChrisRackauckas** [comment]
let's merge and auto-build

**Comment by agerlach** [comment]
Do we need to update DEU in Project.toml? or is that handled automatically. It may be pointing to my fork

**Comment by ChrisRackauckas** [comment]
the bots will add compats.

**Comment by agerlach** [comment]
Even if I had it explicitly pointing to my fork?

**Comment by ChrisRackauckas** [comment]
that's all in the new release right?

**Comment by agerlach** [comment]
yes

**Comment by ChrisRackauckas** [comment]
then it should all be good now. 🤞

**Comment by agerlach** [comment]
Cool. How long does this usually take? Also, I am using GPU to show batch in one tutorial. Will that be cool with the bot?

**Comment by ChrisRackauckas** [comment]
the bot does have GPUs. It's just running after the dynamical benchmarks right now.

**Pull request merged**
