### PR TITLE
Use the new SciMLBenchmarks BuildKite system

### LINKED ISSUE #377: No more Pkg.Display?
In the [code for generating the footer](https://github.com/SciML/SciMLTutorials.jl/blob/1ca51b590a0a8f3b4e16b479bc9a6842a03c4f76/src/SciMLTutorials.jl#L97):

```julia
pkgs = Pkg.Display.status(Pkg.API.Context(), use_as_api=true);
```

`Pkg.Display` doesn't seem to exist any more.

### PR DESCRIPTION
**Pull request by MaxCan-Code**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
We need to update this repo to use the new SciMLBenchmarks BuildKite system.

**Comment by ChrisRackauckas** [comment]
Would you be interested in helping with that?

**Comment by MaxCan-Code** [comment]
Sure, I'll take a look at the [.buildkite](../../SciMLBenchmarks.jl/commits/master/.buildkite). I can also merge the changes from [src/SciMLBenchmarks.jl](../../SciMLBenchmarks.jl/blame/master/src/SciMLBenchmarks.jl) into [src/SciMLTutorials.jl](../blame/master/src/SciMLTutorials.jl)

**Comment by ChrisRackauckas** [comment]
If you have any questions, @staticfloat is the guy to ask.

**Comment by ChrisRackauckas** [comment]
This still isn't running the BuildKite runs. We also need to make the appropriate output repo. @staticfloat might need to take a look.

**Comment by MaxCan-Code** [comment]
If you haven't, you might need to [set up a new pipeline](https://buildkite.com/docs/integrations/github#setting-up-a-new-pipeline-for-a-github-repository) for this repo

**Comment by ChrisRackauckas** [comment]
Just created.

**Comment by MaxCan-Code** [comment]
> We also need to make the appropriate output repo.

Done in my third commit, though SciMLTutorialsOutput doesn't seem to exist yet

**Comment by MaxCan-Code** [comment]
> This still isn't running the BuildKite runs. 

The `.buildkite` folder isn't in this repo yet, @ staticfloat can have a look before merging

**Comment by ChrisRackauckas** [comment]
Oh snap, your branch was named master? 🤦 please don't do that. But haha that's fine. 

I setup the output repo, moved the webserver, and moved the outputs over to that. So hopefully things work? It's worth giving it a try.

**Pull request merged**
